# Generated by Django 2.0.4 on 2018-05-08 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='user_images/default/no-image.jpg', upload_to='user_images/', verbose_name='Profile Pic'),
        ),
    ]
