# Generated by Django 2.0.4 on 2018-05-08 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['likes', 'publish_date', 'edit_date', 'comment_author__name'], 'permissions': (('can_create_comment', 'Can create a comment'), ('can_edit_comment', 'Can edit any comment'), ('can_delete_comment', 'Can remove any comment'))},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['publish_date', 'edit_date', 'post_author__name'], 'permissions': (('can_publish_post', 'Can publish a post'), ('can_edit_post', 'Can edit any posts'), ('can_delete_post', 'Can remove any post'))},
        ),
    ]
